### PR TITLE
Fix common fixtures to use new projects api.

### PR DESCRIPTION
**Pull request by hibooboo2**

### CODE REVIEW

**Comment by hibooboo2** [comment]
This pr will help many of the current tests start to pass. As well as get them in line with the new api. As far as the ones where they can't see fields as a you need to reload the object with admin_client to get the data that you don't have access too.

**Comment by ibuildthecloud** [comment]
@hibooboo2 flake8 errors

**Comment by ibuildthecloud** [comment]
@hibooboo2 By "you" who do you mean?  Who's going to fix all the project tests?

**Comment by hibooboo2** [comment]
By you i mean the person fixing the test. And i can work on some but not working at all tomorrow. Have the wedding.

**Pull request merged**
